Container build workflow should work now

diff --git a/.github/workflows/container_build.yml b/.github/workflows/container_build.yml
--- a/.github/workflows/container_build.yml
+++ b/.github/workflows/container_build.yml
@@ -69,27 +69,6 @@ jobs:
     steps:
       - name: Checkout repository
         uses: *checkout
-      - name: Update Buildah
-        run: &buildah |
-          set -euo pipefail
-
-          case "$(uname -m)" in
-            x86_64) IMAGE_ARCH='amd64' ;;
-            aarch64) IMAGE_ARCH='arm64' ;;
-            *) printf "Invalid architecture" >&2; exit 1 ;;
-          esac
-
-          echo "Installing up to date podman and buildah for $IMAGE_ARCH"
-          sudo parallel --xapply \
-            curl -fsSL https://github.com/{2}/{1}-static/releases/latest/download/{1}{3}-${IMAGE_ARCH}.tar.gz \
-              '|' tar --strip-component {4} -xzf - -C {5} \
-            ::: podman buildah ::: mgoltzsche HeavenVolkoff ::: -linux '' ::: 1 0 ::: / /usr/local/bin/
-
-          # Workaround issues between custom podman installation and apparmor
-          sudo sed -Ei \
-            's!^profile podman /usr/bin/podman !profile podman /usr/{bin,local/bin}/podman !' \
-            /etc/apparmor.d/podman
-          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
       - id: restore
         name: Restore cached image
         uses: &restore actions/cache/restore@v4
@@ -180,7 +159,21 @@ jobs:
         uses: *metadata_action
         with: *metadata
       - name: Update Buildah
-        run: *buildah
+        run: |
+          set -euo pipefail
+
+          case "$(uname -m)" in
+            x86_64) IMAGE_ARCH='amd64' ;;
+            aarch64) IMAGE_ARCH='arm64' ;;
+            *) printf "Invalid architecture" >&2; exit 1 ;;
+          esac
+
+          echo "Installing up to date buildah for $IMAGE_ARCH"
+          curl -fsSL https://github.com/HeavenVolkoff/buildah-static/releases/latest/download/buildah-${IMAGE_ARCH:?}.tar.gz \
+            | tar -xzf - -C /usr/local/bin/
+
+          # Workaround issues between custom buildah installation and apparmor
+          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
       - id: create_manifest
         name: Create multi-arch manifest
         env:
